export const SERVER_SUB_TYPE = {
  0: "Client",
  1: "Gate",
  2: "Cabin",
  3: "Login",
  4: "DB Proxy",
  5: "Center",
  6: "World",
  7: "Party",
  8: "Guild",
  9: "Payment",
  10: "Third Party",
  11: "Ranking",
  12: "GM",
  13: "Info",
  14: "Social",
  15: "Chat",
  16: "Indun",
  17: "Scheduler",
  18: "Exchange",
  100: "Test Client",
  101: "Test Server",
};
export const SERVER_TYPE = {
  0: "Client",
  1: "Gate",
  2: "Cabin",
  3: "Login",
  4: "DB Proxy",
  5: "Center",
  6: "World",
  7: "Party",
  8: "Guild",
  9: "Payment",
  10: "Third Party",
  11: "Ranking",
  12: "GM",
  13: "Info",
  14: "Social",
  15: "Chat",
  16: "Action Log",
  17: "Scheduler",
  18: "Exchange",
  99: "All",
  100: "Test Client",
  101: "Test Server",
};
