/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 10
    }
  },
  {
    name: 'announcement',
    path: '/announcement',
    component: 'layout.base',
    meta: {
      title: 'announcement',
      i18nKey: 'route.announcement'
    },
    children: [
      {
        name: 'announcement_activityimages',
        path: '/announcement/activityimages',
        component: 'view.announcement_activityimages',
        meta: {
          title: 'announcement_activityimages',
          i18nKey: 'route.announcement_activityimages'
        }
      },
      {
        name: 'announcement_maintenance',
        path: '/announcement/maintenance',
        component: 'view.announcement_maintenance',
        meta: {
          title: 'announcement_maintenance',
          i18nKey: 'route.announcement_maintenance'
        }
      },
      {
        name: 'announcement_notice',
        path: '/announcement/notice',
        component: 'view.announcement_notice',
        meta: {
          title: 'announcement_notice',
          i18nKey: 'route.announcement_notice'
        }
      },
      {
        name: 'announcement_notifications',
        path: '/announcement/notifications',
        component: 'view.announcement_notifications',
        meta: {
          title: 'announcement_notifications',
          i18nKey: 'route.announcement_notifications'
        }
      }
    ]
  },
  {
    name: 'business',
    path: '/business',
    component: 'layout.base',
    meta: {
      title: 'business',
      i18nKey: 'route.business'
    },
    children: [
      {
        name: 'business_gemsshop',
        path: '/business/gemsshop',
        component: 'view.business_gemsshop',
        meta: {
          title: 'business_gemsshop',
          i18nKey: 'route.business_gemsshop'
        }
      },
      {
        name: 'business_orders',
        path: '/business/orders',
        component: 'view.business_orders',
        meta: {
          title: 'business_orders',
          i18nKey: 'route.business_orders'
        }
      },
      {
        name: 'business_products',
        path: '/business/products',
        component: 'view.business_products',
        meta: {
          title: 'business_products',
          i18nKey: 'route.business_products'
        }
      }
    ]
  },
  {
    name: 'channel',
    path: '/channel',
    component: 'layout.base',
    meta: {
      title: 'channel',
      i18nKey: 'route.channel'
    },
    children: [
      {
        name: 'channel_channellist',
        path: '/channel/channellist',
        component: 'view.channel_channellist',
        meta: {
          title: 'channel_channellist',
          i18nKey: 'route.channel_channellist'
        }
      }
    ]
  },
  {
    name: 'game',
    path: '/game',
    component: 'layout.base',
    meta: {
      title: 'game',
      i18nKey: 'route.game'
    },
    children: [
      {
        name: 'game_list',
        path: '/game/list',
        component: 'view.game_list',
        meta: {
          title: 'game_list',
          i18nKey: 'route.game_list'
        }
      }
    ]
  },
  {
    name: 'giftmanage',
    path: '/giftmanage',
    component: 'layout.base',
    meta: {
      title: 'giftmanage',
      i18nKey: 'route.giftmanage'
    },
    children: [
      {
        name: 'giftmanage_giftactivityconfig',
        path: '/giftmanage/giftactivityconfig',
        component: 'view.giftmanage_giftactivityconfig',
        meta: {
          title: 'giftmanage_giftactivityconfig',
          i18nKey: 'route.giftmanage_giftactivityconfig'
        }
      },
      {
        name: 'giftmanage_giftcode',
        path: '/giftmanage/giftcode',
        component: 'view.giftmanage_giftcode',
        meta: {
          title: 'giftmanage_giftcode',
          i18nKey: 'route.giftmanage_giftcode'
        }
      },
      {
        name: 'giftmanage_redeemrecord',
        path: '/giftmanage/redeemrecord',
        component: 'view.giftmanage_redeemrecord',
        meta: {
          title: 'giftmanage_redeemrecord',
          i18nKey: 'route.giftmanage_redeemrecord'
        }
      }
    ]
  },
  {
    name: 'guild',
    path: '/guild',
    component: 'layout.base',
    meta: {
      title: 'guild',
      i18nKey: 'route.guild'
    },
    children: [
      {
        name: 'guild_guildmail',
        path: '/guild/guildmail',
        component: 'view.guild_guildmail',
        meta: {
          title: 'guild_guildmail',
          i18nKey: 'route.guild_guildmail'
        }
      },
      {
        name: 'guild_list',
        path: '/guild/list',
        component: 'view.guild_list',
        meta: {
          title: 'guild_list',
          i18nKey: 'route.guild_list'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_gmlog',
        path: '/log/gmlog',
        component: 'view.log_gmlog',
        meta: {
          title: 'log_gmlog',
          i18nKey: 'route.log_gmlog'
        }
      },
      {
        name: 'log_logininfor',
        path: '/log/logininfor',
        component: 'view.log_logininfor',
        meta: {
          title: 'log_logininfor',
          i18nKey: 'route.log_logininfor'
        }
      },
      {
        name: 'log_operlog',
        path: '/log/operlog',
        meta: {
          title: 'log_operlog',
          i18nKey: 'route.log_operlog'
        },
        children: [
          {
            name: 'log_operlog_logininfo',
            path: '/log/operlog/logininfo',
            component: 'view.log_operlog_logininfo',
            meta: {
              title: 'log_operlog_logininfo',
              i18nKey: 'route.log_operlog_logininfo'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ltv',
    path: '/ltv',
    component: 'layout.base',
    meta: {
      title: 'ltv',
      i18nKey: 'route.ltv'
    },
    children: [
      {
        name: 'ltv_ltvpay',
        path: '/ltv/ltvpay',
        component: 'view.ltv_ltvpay',
        meta: {
          title: 'ltv_ltvpay',
          i18nKey: 'route.ltv_ltvpay'
        }
      },
      {
        name: 'ltv_ltvuser',
        path: '/ltv/ltvuser',
        component: 'view.ltv_ltvuser',
        meta: {
          title: 'ltv_ltvuser',
          i18nKey: 'route.ltv_ltvuser'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_corec',
        path: '/monitor/corec',
        component: 'view.monitor_corec',
        meta: {
          title: 'monitor_corec',
          i18nKey: 'route.monitor_corec'
        }
      },
      {
        name: 'monitor_dev',
        path: '/monitor/dev',
        component: 'view.monitor_dev',
        meta: {
          title: 'monitor_dev',
          i18nKey: 'route.monitor_dev'
        },
        children: [
          {
            name: 'monitor_dev_modules',
            path: '/monitor/dev/modules',
            component: 'view.monitor_dev_modules',
            meta: {
              title: 'monitor_dev_modules',
              i18nKey: 'route.monitor_dev_modules'
            }
          }
        ]
      },
      {
        name: 'monitor_job',
        path: '/monitor/job',
        component: 'view.monitor_job',
        meta: {
          title: 'monitor_job',
          i18nKey: 'route.monitor_job'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      }
    ]
  },
  {
    name: 'operate',
    path: '/operate',
    component: 'layout.base',
    meta: {
      title: 'operate',
      i18nKey: 'route.operate'
    },
    children: [
      {
        name: 'operate_mail',
        path: '/operate/mail',
        component: 'view.operate_mail',
        meta: {
          title: 'operate_mail',
          i18nKey: 'route.operate_mail'
        }
      },
      {
        name: 'operate_multiple',
        path: '/operate/multiple',
        component: 'view.operate_multiple',
        meta: {
          title: 'operate_multiple',
          i18nKey: 'route.operate_multiple'
        }
      },
      {
        name: 'operate_server',
        path: '/operate/server',
        component: 'view.operate_server',
        meta: {
          title: 'operate_server',
          i18nKey: 'route.operate_server'
        }
      }
    ]
  },
  {
    name: 'overview',
    path: '/overview',
    component: 'layout.base',
    meta: {
      title: 'overview',
      i18nKey: 'route.overview'
    },
    children: [
      {
        name: 'overview_overviewaadd',
        path: '/overview/overviewaadd',
        component: 'view.overview_overviewaadd',
        meta: {
          title: 'overview_overviewaadd',
          i18nKey: 'route.overview_overviewaadd'
        }
      },
      {
        name: 'overview_overviewrole',
        path: '/overview/overviewrole',
        component: 'view.overview_overviewrole',
        meta: {
          title: 'overview_overviewrole',
          i18nKey: 'route.overview_overviewrole'
        }
      },
      {
        name: 'overview_overviewuser',
        path: '/overview/overviewuser',
        component: 'view.overview_overviewuser',
        meta: {
          title: 'overview_overviewuser',
          i18nKey: 'route.overview_overviewuser'
        }
      }
    ]
  },
  {
    name: 'questionnaire',
    path: '/questionnaire',
    component: 'layout.base',
    meta: {
      title: 'questionnaire',
      i18nKey: 'route.questionnaire'
    },
    children: [
      {
        name: 'questionnaire_config',
        path: '/questionnaire/config',
        component: 'view.questionnaire_config',
        meta: {
          title: 'questionnaire_config',
          i18nKey: 'route.questionnaire_config'
        },
        children: [
          {
            name: 'questionnaire_config_surveyrecord',
            path: '/questionnaire/config/surveyrecord',
            component: 'view.questionnaire_config_surveyrecord',
            meta: {
              title: 'questionnaire_config_surveyrecord',
              i18nKey: 'route.questionnaire_config_surveyrecord'
            }
          }
        ]
      },
      {
        name: 'questionnaire_surveyrecord',
        path: '/questionnaire/surveyrecord',
        component: 'view.questionnaire_surveyrecord',
        meta: {
          title: 'questionnaire_surveyrecord',
          i18nKey: 'route.questionnaire_surveyrecord'
        }
      }
    ]
  },
  {
    name: 'retention',
    path: '/retention',
    component: 'layout.base',
    meta: {
      title: 'retention',
      i18nKey: 'route.retention'
    },
    children: [
      {
        name: 'retention_payretention',
        path: '/retention/payretention',
        component: 'view.retention_payretention',
        meta: {
          title: 'retention_payretention',
          i18nKey: 'route.retention_payretention'
        }
      },
      {
        name: 'retention_retentionrole',
        path: '/retention/retentionrole',
        component: 'view.retention_retentionrole',
        meta: {
          title: 'retention_retentionrole',
          i18nKey: 'route.retention_retentionrole'
        }
      },
      {
        name: 'retention_retentionuser',
        path: '/retention/retentionuser',
        component: 'view.retention_retentionuser',
        meta: {
          title: 'retention_retentionuser',
          i18nKey: 'route.retention_retentionuser'
        }
      }
    ]
  },
  {
    name: 'server',
    path: '/server',
    component: 'layout.base',
    meta: {
      title: 'server',
      i18nKey: 'route.server'
    },
    children: [
      {
        name: 'server_log',
        path: '/server/log',
        component: 'view.server_log',
        meta: {
          title: 'server_log',
          i18nKey: 'route.server_log'
        }
      },
      {
        name: 'server_region',
        path: '/server/region',
        component: 'view.server_region',
        meta: {
          title: 'server_region',
          i18nKey: 'route.server_region'
        }
      },
      {
        name: 'server_servercross',
        path: '/server/servercross',
        component: 'view.server_servercross',
        meta: {
          title: 'server_servercross',
          i18nKey: 'route.server_servercross'
        }
      },
      {
        name: 'server_serverfile',
        path: '/server/serverfile',
        component: 'view.server_serverfile',
        meta: {
          title: 'server_serverfile',
          i18nKey: 'route.server_serverfile'
        }
      },
      {
        name: 'server_servergroup',
        path: '/server/servergroup',
        component: 'view.server_servergroup',
        meta: {
          title: 'server_servergroup',
          i18nKey: 'route.server_servergroup'
        }
      },
      {
        name: 'server_serveritem',
        path: '/server/serveritem',
        component: 'view.server_serveritem',
        meta: {
          title: 'server_serveritem',
          i18nKey: 'route.server_serveritem'
        },
        children: [
          {
            name: 'server_serveritem_detail',
            path: '/server/serveritem/detail',
            component: 'view.server_serveritem_detail',
            meta: {
              title: 'server_serveritem_detail',
              i18nKey: 'route.server_serveritem_detail'
            }
          }
        ]
      },
      {
        name: 'server_white',
        path: '/server/white',
        component: 'view.server_white',
        meta: {
          title: 'server_white',
          i18nKey: 'route.server_white'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:monitor-dashboard'
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user'
    },
    children: [
      {
        name: 'user_activate',
        path: '/user/activate',
        component: 'view.user_activate',
        meta: {
          title: 'user_activate',
          i18nKey: 'route.user_activate'
        }
      },
      {
        name: 'user_player',
        path: '/user/player',
        component: 'view.user_player',
        meta: {
          title: 'user_player',
          i18nKey: 'route.user_player'
        },
        children: [
          {
            name: 'user_player_detail',
            path: '/user/player/detail',
            component: 'view.user_player_detail',
            meta: {
              title: 'user_player_detail',
              i18nKey: 'route.user_player_detail'
            }
          }
        ]
      },
      {
        name: 'user_rolelist',
        path: '/user/rolelist',
        component: 'view.user_rolelist',
        meta: {
          title: 'user_rolelist',
          i18nKey: 'route.user_rolelist'
        }
      },
      {
        name: 'user_users',
        path: '/user/users',
        component: 'view.user_users',
        meta: {
          title: 'user_users',
          i18nKey: 'route.user_users'
        }
      },
      {
        name: 'user_white',
        path: '/user/white',
        component: 'view.user_white',
        meta: {
          title: 'user_white',
          i18nKey: 'route.user_white'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'viewoperation',
    path: '/viewoperation',
    component: 'layout.base',
    meta: {
      title: 'viewoperation',
      i18nKey: 'route.viewoperation'
    },
    children: [
      {
        name: 'viewoperation_activitygm',
        path: '/viewoperation/activitygm',
        component: 'view.viewoperation_activitygm',
        meta: {
          title: 'viewoperation_activitygm',
          i18nKey: 'route.viewoperation_activitygm'
        }
      },
      {
        name: 'viewoperation_createtemplate',
        path: '/viewoperation/createtemplate',
        component: 'view.viewoperation_createtemplate',
        meta: {
          title: 'viewoperation_createtemplate',
          i18nKey: 'route.viewoperation_createtemplate'
        }
      },
      {
        name: 'viewoperation_gmtemplateparams',
        path: '/viewoperation/gmtemplateparams',
        component: 'view.viewoperation_gmtemplateparams',
        meta: {
          title: 'viewoperation_gmtemplateparams',
          i18nKey: 'route.viewoperation_gmtemplateparams'
        }
      },
      {
        name: 'viewoperation_serveractivity',
        path: '/viewoperation/serveractivity',
        component: 'view.viewoperation_serveractivity',
        meta: {
          title: 'viewoperation_serveractivity',
          i18nKey: 'route.viewoperation_serveractivity'
        }
      },
      {
        name: 'viewoperation_startactivity',
        path: '/viewoperation/startactivity',
        component: 'view.viewoperation_startactivity',
        meta: {
          title: 'viewoperation_startactivity',
          i18nKey: 'route.viewoperation_startactivity'
        }
      },
      {
        name: 'viewoperation_viewlogs',
        path: '/viewoperation/viewlogs',
        component: 'view.viewoperation_viewlogs',
        meta: {
          title: 'viewoperation_viewlogs',
          i18nKey: 'route.viewoperation_viewlogs'
        }
      }
    ]
  }
];
